[source]
paths = ["src"]
includes = ["./vendor", "_ide_helper_models.php", "database"]
excludes = [
  "./vendor/composer",
]

[analyzer]
find-unused-expressions = true
find-unused-definitions = true
analyze-dead-code = true
check-throws = true
check-missing-override = true
find-unused-parameters = true
check-missing-type-hints = true
check-closure-missing-type-hints = false
check-arrow-function-missing-type-hints = false
enforce-class-finality = true
require-api-or-internal = false

# Enable strict checks
strict-list-index-checks = true
no-boolean-literal-comparison = true

# Disable lenient behaviors
allow-possibly-undefined-array-keys = false
trust-existence-checks = false

ignore = [
  { code = "missing-template-parameter", in = "app/" },
  { code = "mixed-method-access", in = "app/" },
  { code = "mixed-assignment", in = "app/" },
  { code = "imprecise-type", in = "app/" },
]

plugins = ["psl", "laravel"]

[formatter]
print-width = 180
tab-width = 4
use-tabs = false
null-type-hint = "question"
space-after-logical-not-unary-prefix-operator = true
space-before-arrow-function-parameter-list-parenthesis = true
always-break-named-arguments-list = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true

[linter]
integrations = ["symfony", "laravel"]

[linter.rules]
class-name = { psr = false }
cyclomatic-complexity = { enabled = false }
excessive-parameter-list = { enabled = false }
halstead = { enabled = false }
interface-name = { psr = false }
kan-defect = { enabled = false }
literal-named-argument = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
#no-boolean-literal-comparison = { enabled = false }
no-debug-symbols = { enabled = false }
no-else-clause = { enabled = false }
no-empty = { enabled = false }
no-error-control-operator = { enabled = false }
no-literal-password = { enabled = false }
no-request-all = { enabled = false }
no-shorthand-ternary = { enabled = false }
prefer-first-class-callable = { enabled = false }
too-many-enum-cases = { enabled = false }
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }
yoda-conditions = { enabled = false }
# no-untagged-fixme = { enabled = false }
# no-untagged-todo = { enabled = false }
# require-identity-comparison = { enabled = false }
# require-parameter-type = { ignore_arrow_function = true, ignore_closure = true }
# require-return-type = { enabled = false }
# strict-assertions = { enabled = false }
# trait = { psr = false }
