[source]
paths = ["src"]
includes = ["./vendor"]
excludes = [
  "./vendor/composer",
  "./vendor/symfony/polyfill-iconv/Resources/charset",
]

#[analyzer]
#nullable-issues = false
#ignore = ["mixed-argument"]

[formatter]
print-width = 180
tab-width = 4
use-tabs = false
null-type-hint = "question"
space-after-logical-not-unary-prefix-operator = true
space-before-arrow-function-parameter-list-parenthesis = true
always-break-named-arguments-list = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true

[linter]
integrations = ["symfony", "laravel"]

[linter.rules]
# class = { psr = false }
cyclomatic-complexity = { enabled = false }
excessive-parameter-list = { enabled = false }
halstead = { enabled = false }
# interface = { psr = false }
kan-defect = { enabled = false }
literal-named-argument = { enabled = false }
# long-inheritance-chain = { enabled = false }
# no-assignment-in-condition = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-boolean-literal-comparison = { enabled = false }
no-else-clause = { enabled = false }
# no-empty-comments = { enabled = false }
# no-empty-construct = { enabled = false }
no-error-control-operator = { enabled = false }
no-literal-password = { enabled = false }
no-shorthand-ternary = { enabled = false }
# no-untagged-fixme = { enabled = false }
# no-untagged-todo = { enabled = false }
# override-attribute = { enabled = false }
# redundant-file = { enabled = false }
# require-identity-comparison = { enabled = false }
# require-parameter-type = { ignore_arrow_function = true, ignore_closure = true }
# require-return-type = { enabled = false }
# require-strict-behavior = { enabled = false }
strict-assertions = { enabled = false }
too-many-enum-cases = { enabled = false }
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }
# trait = { psr = false }
yoda-conditions = { enabled = false }
